swagger: '2.0'
info:
  version: "1.0.0"
  title: 'APE'
  description: 'Demo'

host: virtserver.swaggerhub.com
basePath: /J591/sample/1.0.0
schemes:
 - https

paths:
  /apes:
    get:
      tags:
      - Company
      summary: Find all apes in the company
      description: More detail here.
      x-swagger-router-controller: Apes
      produces: 
      - application/json
      responses:
        200: 
          description: We've got the apes.
          schema:
            type: array
            items: 
              type: object
              properties:
                name:
                  type: string
                  description: Extra important comment
                email:
                  type: string
          examples:
            application/json:
            - name: Jesper Blåbärsöl
              email: jesper@kalle.com
                
  /apes/{email}:
    get: 
      tags:
      - Company
      description: Get a specific ape by email
      x-swagger-router-controller: Apes
      parameters:
      - in: path
        name: email
        type: string
        required: true
      produces:
      - application/json
      responses:
        200:
          description: We've got the apes.
          schema:
            type: object
            properties:
              name:
                type: string
                description: Extra important comment
              email:
                type: string
          examples:
            application/json:
              items:
              - name: Jesper Blåbärsöl
                email: jesper@kalle.com